# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
subtitle: Design, development, productivity -- notes and explorations.
email:
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /blog/:year/:month/:day/:title/
url: "http://rwx.io" # the base hostname & protocol for your site
logo: profile.jpg 
description: > # this means to ignore newlines until "baseurl:"
  Design, development, productivity – notes and explorations.
twitter_username: rwxstar 
github_username:  fooqri
exclude: [.bundle, bin, vendor]

# Build settings
markdown: kramdown

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
popular_posts_count: 10      # Posts in the sidebar Popular Posts section
recent_posts: 10       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
#default_asides: [asides/nav.html, custom/asides/popular_posts.html, asides/recent_posts.html, asides/twitter.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]
default_asides: [asides/recent_posts.html, custom/asides/popular_posts.html, asides/twitter.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# Plugins
twitter:
  username:            rwxstar             # Add your Twitter handle
  tweet_count:         false              # Show number of shares on Twitter
  size:                normal             # Or large
  embedded_link_color:                    # Set link color for embedded tweets

  follow_count:        false              # Show number of followers
  tweet_message:       ":title by :username :hashtags - :url" # With Tweet button Twitter add the URL last
  tweet_link_text:     Twitter            # Configure the link text
  tweet_link_title:    Share on Twitter   # Share link title
  profile_link_text:   Follow :username
  profile_link_title:  Follow :username on Twitter  # Profile link title text

disqus:
  shortname: goddio                                # Your site's disqus identifier
